import { describe, expect, it } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { parseVectorIndexNpz } from './localVectorIndexParser';

// Fixture generated by the REAL Python serialization code
// (backend/scripts/generate_vector_index_parity_fixture.py), which mirrors
// storage_utils._serialize_vector_index byte-for-byte. This is the
// highest-risk new code in the Phase B semantic-search work (a from-scratch
// ZIP+NPY binary parser) -- verified against real numpy output, not just
// against this parser's own assumptions about the format.
const NPZ_PATH = path.resolve(__dirname, '../../../backend/tests/fixtures/vector_index_parity.npz');
const EXPECTED_PATH = path.resolve(__dirname, '../../../backend/tests/fixtures/vector_index_parity.expected.json');

interface Expected {
    rowKeys: string[];
    sourceVersion: string;
    embeddingVersion: string;
    updatedAt: string;
    embeddingsShape: [number, number];
    embeddingsFlat: number[];
}

const expected: Expected = JSON.parse(fs.readFileSync(EXPECTED_PATH, 'utf-8'));

describe('parseVectorIndexNpz against a real numpy-generated fixture', () => {
    it('parses row keys and metadata strings exactly', async () => {
        const buffer = fs.readFileSync(NPZ_PATH);
        const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
        const result = await parseVectorIndexNpz(arrayBuffer);

        expect(result.rowKeys).toEqual(expected.rowKeys);
        expect(result.sourceVersion).toBe(expected.sourceVersion);
        expect(result.embeddingVersion).toBe(expected.embeddingVersion);
        expect(result.updatedAt).toBe(expected.updatedAt);
        expect(result.dimension).toBe(expected.embeddingsShape[1]);
        expect(result.embeddings.length).toBe(expected.embeddingsShape[0]);
    });

    it('parses embedding floats exactly (including the unicode filename, a UTF-32 decode edge case)', async () => {
        const buffer = fs.readFileSync(NPZ_PATH);
        const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
        const result = await parseVectorIndexNpz(arrayBuffer);

        const [rowCount, dim] = expected.embeddingsShape;
        for (let i = 0; i < rowCount; i += 1) {
            for (let d = 0; d < dim; d += 1) {
                const actual = result.embeddings[i][d];
                const wanted = expected.embeddingsFlat[i * dim + d];
                expect(actual).toBeCloseTo(wanted, 6);
            }
        }

        // unicode_café_日本.jpg -- exercises non-BMP-adjacent accented and
        // CJK codepoints through the hand-rolled UTF-32LE decoder.
        expect(result.rowKeys).toContain('unicode_café_日本.jpg');
    });
});
