/**
 * Minimal ZIP + NumPy .npy parser for the per-user vector-index blob
 * (backend/storage_utils.py's _serialize_vector_index / np.savez_compressed)
 * -- downloaded directly from blob storage for client-side semantic search
 * (see backend-cpu-optimization-2026-09 memory, Phase B). Deliberately
 * narrow: only the exact shapes this one blob format uses (2D <f4 arrays,
 * 1-element <U<N> unicode string arrays), not a general-purpose reader.
 *
 * Verified against a real .npz file generated by the actual Python
 * serialization code, not just against this file's own assumptions about
 * the format -- see localVectorIndexParser.test.ts.
 */

interface ZipEntry {
    compressionMethod: number;
    compressedSize: number;
    localHeaderOffset: number;
}

const textFrom = (bytes: Uint8Array, start: number, len: number): string => {
    let s = '';
    for (let i = 0; i < len; i += 1) {
        s += String.fromCharCode(bytes[start + i]);
    }
    return s;
};

const readUint32LE = (view: DataView, offset: number): number => view.getUint32(offset, true);
const readUint16LE = (view: DataView, offset: number): number => view.getUint16(offset, true);

const EOCD_SIGNATURE = 0x06054b50;
const CENTRAL_DIR_SIGNATURE = 0x02014b50;
const LOCAL_FILE_SIGNATURE = 0x04034b50;

// Scans backward for the End Of Central Directory record. These blobs never
// carry a ZIP comment (numpy's zipfile writer doesn't add one), so the EOCD
// is always in the last 22 bytes -- backward scanning a short trailing
// window instead of assuming a fixed offset is what makes this robust to
// that still being true if it ever isn't.
const findEndOfCentralDirectory = (view: DataView, buffer: Uint8Array): number => {
    const maxCommentLength = 65535;
    const searchStart = Math.max(0, buffer.length - 22 - maxCommentLength);
    for (let i = buffer.length - 22; i >= searchStart; i -= 1) {
        if (readUint32LE(view, i) === EOCD_SIGNATURE) {
            return i;
        }
    }
    throw new Error('vector_index_zip_eocd_not_found');
};

const parseCentralDirectory = (buffer: Uint8Array, view: DataView): Map<string, ZipEntry> => {
    const eocdOffset = findEndOfCentralDirectory(view, buffer);
    const entryCount = readUint16LE(view, eocdOffset + 10);
    const centralDirOffset = readUint32LE(view, eocdOffset + 16);

    const entries = new Map<string, ZipEntry>();
    let offset = centralDirOffset;
    for (let i = 0; i < entryCount; i += 1) {
        if (readUint32LE(view, offset) !== CENTRAL_DIR_SIGNATURE) {
            throw new Error('vector_index_zip_central_directory_corrupt');
        }
        const compressionMethod = readUint16LE(view, offset + 10);
        const compressedSize = readUint32LE(view, offset + 20);
        const fileNameLength = readUint16LE(view, offset + 28);
        const extraFieldLength = readUint16LE(view, offset + 30);
        const fileCommentLength = readUint16LE(view, offset + 32);
        const localHeaderOffset = readUint32LE(view, offset + 42);
        const fileName = textFrom(buffer, offset + 46, fileNameLength);
        entries.set(fileName, { compressionMethod, compressedSize, localHeaderOffset });
        offset += 46 + fileNameLength + extraFieldLength + fileCommentLength;
    }
    return entries;
};

const extractCompressedBytes = (buffer: Uint8Array, view: DataView, entry: ZipEntry): Uint8Array => {
    const offset = entry.localHeaderOffset;
    if (readUint32LE(view, offset) !== LOCAL_FILE_SIGNATURE) {
        throw new Error('vector_index_zip_local_header_corrupt');
    }
    const fileNameLength = readUint16LE(view, offset + 26);
    const extraFieldLength = readUint16LE(view, offset + 28);
    const dataStart = offset + 30 + fileNameLength + extraFieldLength;
    return buffer.subarray(dataStart, dataStart + entry.compressedSize);
};

const inflateRaw = async (compressed: Uint8Array): Promise<Uint8Array> => {
    const stream = new Response(compressed).body!.pipeThrough(new DecompressionStream('deflate-raw'));
    const buffer = await new Response(stream).arrayBuffer();
    return new Uint8Array(buffer);
};

// method 0 = stored (no compression), 8 = deflate -- np.savez_compressed
// always uses 8, but np.savez (uncompressed) would use 0; support both since
// nothing prevents a future change here from switching functions.
const decompressZipEntry = async (buffer: Uint8Array, view: DataView, entry: ZipEntry): Promise<Uint8Array> => {
    const compressed = extractCompressedBytes(buffer, view, entry);
    if (entry.compressionMethod === 0) {
        return compressed;
    }
    if (entry.compressionMethod === 8) {
        return inflateRaw(compressed);
    }
    throw new Error(`vector_index_zip_unsupported_compression_method:${entry.compressionMethod}`);
};

interface NpyHeader {
    descr: string;
    shape: number[];
    dataOffset: number;
}

const parseNpyHeader = (bytes: Uint8Array): NpyHeader => {
    const magic = textFrom(bytes, 0, 6);
    if (magic !== '\x93NUMPY') {
        throw new Error('npy_bad_magic');
    }
    const majorVersion = bytes[6];
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    let headerLength: number;
    let headerStart: number;
    if (majorVersion === 1) {
        headerLength = readUint16LE(view, 8);
        headerStart = 10;
    } else {
        // v2.0+ uses a 4-byte little-endian header length instead of 2-byte.
        headerLength = readUint32LE(view, 8);
        headerStart = 12;
    }
    const headerText = textFrom(bytes, headerStart, headerLength);

    // The header is a literal Python dict repr, always with these exact
    // three keys for arrays this codebase ever writes -- regex-extracting
    // the fields we need rather than writing a general Python-literal
    // parser for a format that's otherwise fixed by numpy's own writer.
    const descrMatch = headerText.match(/'descr':\s*'([^']+)'/);
    const shapeMatch = headerText.match(/'shape':\s*\(([^)]*)\)/);
    if (!descrMatch || !shapeMatch) {
        throw new Error('npy_header_unparseable');
    }
    const shape = shapeMatch[1]
        .split(',')
        .map((part) => part.trim())
        .filter((part) => part.length > 0)
        .map((part) => parseInt(part, 10));

    return { descr: descrMatch[1], shape, dataOffset: headerStart + headerLength };
};

const parseFloat32Array = (bytes: Uint8Array, header: NpyHeader): Float32Array => {
    // Float32Array requires a 4-byte-aligned buffer offset -- slice() copies
    // into a fresh zero-offset ArrayBuffer rather than risk a misaligned
    // view into the original (possibly non-4-byte-aligned) buffer.
    const dataBytes = bytes.slice(header.dataOffset);
    return new Float32Array(dataBytes.buffer, dataBytes.byteOffset, dataBytes.length / 4);
};

// NumPy's '<U<N>' dtype is fixed-width UTF-32LE (4 bytes/char, NUL-padded),
// NOT UTF-8 -- browsers' TextDecoder has no utf-32 codec, so this decodes it
// by hand, one 4-byte code unit at a time via String.fromCodePoint (which
// correctly emits a surrogate pair for any codepoint above the BMP).
const parseUnicodeString = (bytes: Uint8Array, header: NpyHeader): string => {
    const match = header.descr.match(/^<U(\d+)$/);
    if (!match) {
        throw new Error(`npy_unexpected_string_dtype:${header.descr}`);
    }
    const charCount = parseInt(match[1], 10);
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    let result = '';
    for (let i = 0; i < charCount; i += 1) {
        const codePoint = view.getUint32(header.dataOffset + i * 4, true);
        if (codePoint === 0) {
            break; // NUL padding marks the end of the real string content.
        }
        result += String.fromCodePoint(codePoint);
    }
    return result;
};

export interface ParsedVectorIndex {
    rowKeys: string[];
    embeddingVersion: string;
    sourceVersion: string;
    updatedAt: string;
    dimension: number;
    /** embeddings[i] is the L2-normalized-at-storage-time vector for rowKeys[i]. */
    embeddings: Float32Array[];
}

export const parseVectorIndexNpz = async (buffer: ArrayBuffer): Promise<ParsedVectorIndex> => {
    const bytes = new Uint8Array(buffer);
    const view = new DataView(buffer);
    const entries = parseCentralDirectory(bytes, view);

    const readArray = async (name: string): Promise<{ bytes: Uint8Array; header: NpyHeader }> => {
        const entry = entries.get(name);
        if (!entry) {
            throw new Error(`vector_index_missing_array:${name}`);
        }
        const decompressed = await decompressZipEntry(bytes, view, entry);
        const header = parseNpyHeader(decompressed);
        return { bytes: decompressed, header };
    };

    const [embeddingsArr, rowKeysArr, sourceVersionArr, embeddingVersionArr, updatedAtArr] = await Promise.all([
        readArray('embeddings.npy'),
        readArray('row_keys.npy'),
        readArray('source_version.npy'),
        readArray('embedding_version.npy'),
        readArray('updated_at.npy'),
    ]);

    if (embeddingsArr.header.descr !== '<f4' || embeddingsArr.header.shape.length !== 2) {
        throw new Error('vector_index_embeddings_shape_unexpected');
    }
    const [rowCount, dimension] = embeddingsArr.header.shape;
    const flat = parseFloat32Array(embeddingsArr.bytes, embeddingsArr.header);
    if (flat.length !== rowCount * dimension) {
        throw new Error('vector_index_embeddings_size_mismatch');
    }

    const rowKeysJson = parseUnicodeString(rowKeysArr.bytes, rowKeysArr.header);
    const rowKeys: unknown = JSON.parse(rowKeysJson);
    if (!Array.isArray(rowKeys) || rowKeys.length !== rowCount) {
        throw new Error('vector_index_row_keys_mismatch');
    }

    const embeddings: Float32Array[] = [];
    for (let i = 0; i < rowCount; i += 1) {
        embeddings.push(flat.subarray(i * dimension, (i + 1) * dimension));
    }

    return {
        rowKeys: rowKeys.map((k) => String(k)),
        embeddingVersion: parseUnicodeString(embeddingVersionArr.bytes, embeddingVersionArr.header),
        sourceVersion: parseUnicodeString(sourceVersionArr.bytes, sourceVersionArr.header),
        updatedAt: parseUnicodeString(updatedAtArr.bytes, updatedAtArr.header),
        dimension,
        embeddings,
    };
};
